### ISSUE TITLE
Setup chart repo & CI

### ISSUE THREAD

**Issue by 4nte** [VolantMQ/helm#2]

**Comment by saikatharryc** [comment]
@4nte  let me know in case you need some hand on this.
and what is the CI provider you are using?
is it possible to use [test-infra](https://github.com/kubernetes/test-infra)?

**Comment by 4nte** [comment]
I'm setting up a Github Actions pipeline to auomate chart releases.
Can you give more insight in what test-infra can do for us? I haven't used it yet.

**Comment by saikatharryc** [comment]
>I'm setting up a Github Actions pipeline to automate chart releases.

That's great!
I'm evaluating if we can use test-infra that is currently used by https://github.com/helm/charts
although it's not CI/CD, it's more of a test suit kind of a thing.

**Comment by 4nte** [comment]
> > I'm setting up a Github Actions pipeline to automate chart releases.
> 
> That's great!
> I'm evaluating if we can use test-infra that is currently used by https://github.com/helm/charts
> although it's not CI/CD, it's more of a test suit kind of a thing.

Cool, I'm working on lint, test and release steps in CI.
I'm almost finished, I just need to resolve this issue with the step "chart-testing (install)", which supposedly fails with 
```
 ✖︎ volantmq => (version: "0.1.4", path: "charts/volantmq") > Error waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
Error installing charts: Error processing charts
```
Even tho when you look at logs of the step, it sucessfully installs the helm chart (using kubernetes-in-docker), but the github action somehow decided it failed.
So far I didn't find anything relevant for this error message.

Here's is the failed CI run:
https://github.com/4nte/helm/pull/2/checks?check_run_id=577039509

**Comment by saikatharryc** [comment]
@4nte  so I believe, we need to add some custom helm timeout.
also, other values as needed. currently, the [ct.yaml ](https://github.com/4nte/helm/actions/runs/75277978/workflow#L20) is not present in the codebase,
refer [here](https://github.com/helm/charts/blob/master/test/ct.yaml#L10) for how we can add timeout and other values.

**Comment by saikatharryc** [comment]
@4nte It worked for me!
here is the thing: https://github.com/saikatharryc/VolantMQ_helm/runs/596017302
(I'm not ashamed to say that, a bit struggle I had to do though for this initially as things were not set in my end.)

and here you go: https://github.com/4nte/helm/pull/3

**Comment by 4nte** [comment]
Well done @saikatharryc! :)
